[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "purlin"
version = "0.2.2"
readme = "README.md"
license = "BSD-3-Clause"
license-files = ["LICENSE"]
description = "Adaptable, template-based substrate for high-performance inter-GPU communication"
requires-python = ">=3.10"
authors = [
    { name = "Osayamen Jonathan Aimuyo", email = "osayamen@stanford.edu" },
]
dependencies = [
      "torch>=2.8.0",
]

[project.urls]
Homepage = "https://github.com/osayamenja/purlin"
Repository = "https://github.com/osayamenja/purlin"

[tool.setuptools]
packages = ["purlin"]

[tool.setuptools.package-data]
purlin = [
    "CMakeLists.txt",
    "CPM.cmake"
]
