[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "tack"
version = "0.1.0"
readme = "README.md"
license = "BSD-3-Clause"
license-files = ["LICENSE"]
description = "Template-based Adaptable Communication for Kernels"
requires-python = ">=3.10"
authors = [
    { name = "Osayamen Jonathan Aimuyo", email = "osayamen@stanford.edu" },
]

[project.urls]
Homepage = "https://github.com/osayamenja/tack"
Repository = "https://github.com/osayamenja/tack"

[tool.setuptools]
packages = ["tack"]
package-dir = { "tack" = "tack-py" }

[tool.setuptools.package-data]
tack = [
    "CMakeLists.txt",
    "cmake/*"
]
